"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../controllers/userController");
const router = (0, express_1.Router)();
router.get('/', userController_1.userGet);
router.post('/', userController_1.userPost);
router.put('/:id', userController_1.userPut);
router.delete('/', userController_1.userDelete);
router.patch('/', userController_1.userPatch);
exports.default = router;
